### PR TITLE
Add vim-galore 中译本和 SpaceVim

### PR DESCRIPTION
**Pull request by wsdjeg**
你好，希望可以添加这两份文档，谢谢

### CODE REVIEW

**Comment by danphamus304** [comment]
https://github.com/justjavac/free-programming-books-zh_CN/commit/8132a652b66bf1711b29ffbe6d580a588a56437c

**Comment by danphamus304** [comment]
wsdjeg:master

**Comment by Bethannfrum** [comment]
wsdjeg:master

**Comment by Bethannfrum** [comment]
Open
		

		
	





On Fri, Mar 30, 2018 at 8:44 AM -0400, "Bethannfrum" <notifications@github.com> wrote:












wsdjeg:master

**Comment by Bethannfrum** [comment]
wsdjeg:master

**Comment by Alexkho82** [comment]
8132a65

**Comment by Alexkho82** [comment]
#619

**Comment by rela2x** [comment]
10129296058

**Comment by cajungitter** [comment]
8132a65

**Pull request closed without merging**
